module.exports.makeCryptographicModuleTemplateAndroid = (key) => {
  return `
// this is autogenerated, dont change within it
package com.reactnativekeysjsi;

public class PrivateKey {
 public static String privatekey="${key}";
}`;
};
