
// this is autogenerated, dont change within it
package com.reactnativekeysjsi;

public class PrivateKey {
 public static String privatekey="++r99tSrk2+LWomyHaBfUvfegAH2BOY6IcpWkfk4M+oc/0xFbf5dl8zHWLJgjIDhjI/3svF1Vm+O71+l1UTNg=";
}