
// this is autogenerated, dont change within it
package com.reactnativekeysjsi;

public class PrivateKey {
 public static String privatekey="pZoshfXIdCfwBqsc57d31atAUMf0lxCX5NWnCtWzHwFa4YazE8aHeQ009f8GiurSFBtjDNMSoog33YYHZtebu0+PrCTX8su4Y1df5FK1Rg==";
}