name: Validate JS

on:
  pull_request:
    paths:
      - ".github/workflows/validate-js.yml"
      - "src/**"
      - "*.json"
      - "*.js"
      - "*.lock"
      - "example/src/**"
      - "example/*.json"
      - "example/*.js"
      - "example/*.lock"
      - "example/*.tsx"

jobs:
  compile:
    name: Compile (tsc)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install node_modules (example/)
        run: yarn --cwd example install --immutable --check-cache

      - name: Do typecheck
        run: |
          yarn typecheck

  lint:
    name: Lint / Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install node_modules (example/)
        run: yarn --cwd example install --immutable --check-cache

      - name: Run Biome with auto-fix
        run: yarn lint

  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run test coverage
        run: yarn test --coverage
